# Generated by Django 4.2.4 on 2023-08-20 14:30

import core.constants
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DrawingBoard",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "unique_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "permission_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "PUBLIC_READ"),
                            (2, "USER_READ"),
                            (3, "USER_READ_WRITE"),
                            (4, "PROTECTED_READ"),
                            (5, "PROTECTED_READ_WRITE"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SharedDrawingBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("can_write", models.BooleanField(default=False)),
                (
                    "drawing_board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="db.drawingboard",
                    ),
                ),
                (
                    "shared_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DrawingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("action_meta", models.TextField()),
                (
                    "action_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "FREEHAND_DRAW"),
                            (2, "DRAW_LINE"),
                            (3, "DRAW_POLYGON"),
                            (4, "WRITE_TEXT"),
                        ],
                        default=core.constants.ActionTypeEnum["FREEHAND_DRAW"],
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField()),
                ("version", models.PositiveSmallIntegerField(default=1)),
                (
                    "drawing_board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="db.drawingboard",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
