# Generated by Django 4.2.4 on 2023-08-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="drawingboard",
            name="description",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="drawingboard",
            name="header",
            field=models.CharField(default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="drawingboard",
            name="permission_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "PUBLIC_READ"),
                    (2, "USER_READ"),
                    (4, "USER_WRITE"),
                    (8, "PROTECTED_READ"),
                    (16, "PROTECTED_WRITE"),
                    (5, "USER_WRITE_PUBLIC_READ"),
                    (17, "PROTECTED_WRITE_PUBLIC_READ"),
                    (12, "USER_WRITE_PROTECTED_READ"),
                ],
                default=1,
            ),
        ),
    ]
