# Generated by Django 4.2.4 on 2023-08-21 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0002_drawingboard_description_drawingboard_header_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drawingsession",
            name="action_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "FREEHAND_DRAW"),
                    (2, "DRAW_LINE"),
                    (3, "DRAW_POLYGON"),
                    (4, "WRITE_TEXT"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="drawingsession",
            name="drawing_board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drawing_sessions",
                to="db.drawingboard",
            ),
        ),
        migrations.AlterField(
            model_name="drawingsession",
            name="ended_at",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="drawingsession",
            name="started_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
